// <auto-generated />
using LottoLab.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LottoLab.Migrations
{
    [DbContext(typeof(LottoLabContext))]
    [Migration("20230717182803_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LottoLab.Models.LotoFacil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Casa_1")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_10")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_11")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_12")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_13")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_14")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_15")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_2")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_3")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_4")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_5")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_6")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_7")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_8")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Casa_9")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Concurso")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("LotoFacil", (string)null);
                });

            modelBuilder.Entity("LottoLab.Models.LotoFacilDelay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Concurso")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("bola1")
                        .HasColumnType("int");

                    b.Property<int>("bola10")
                        .HasColumnType("int");

                    b.Property<int>("bola11")
                        .HasColumnType("int");

                    b.Property<int>("bola12")
                        .HasColumnType("int");

                    b.Property<int>("bola13")
                        .HasColumnType("int");

                    b.Property<int>("bola14")
                        .HasColumnType("int");

                    b.Property<int>("bola15")
                        .HasColumnType("int");

                    b.Property<int>("bola16")
                        .HasColumnType("int");

                    b.Property<int>("bola17")
                        .HasColumnType("int");

                    b.Property<int>("bola18")
                        .HasColumnType("int");

                    b.Property<int>("bola19")
                        .HasColumnType("int");

                    b.Property<int>("bola2")
                        .HasColumnType("int");

                    b.Property<int>("bola20")
                        .HasColumnType("int");

                    b.Property<int>("bola21")
                        .HasColumnType("int");

                    b.Property<int>("bola22")
                        .HasColumnType("int");

                    b.Property<int>("bola23")
                        .HasColumnType("int");

                    b.Property<int>("bola24")
                        .HasColumnType("int");

                    b.Property<int>("bola25")
                        .HasColumnType("int");

                    b.Property<int>("bola3")
                        .HasColumnType("int");

                    b.Property<int>("bola4")
                        .HasColumnType("int");

                    b.Property<int>("bola5")
                        .HasColumnType("int");

                    b.Property<int>("bola6")
                        .HasColumnType("int");

                    b.Property<int>("bola7")
                        .HasColumnType("int");

                    b.Property<int>("bola8")
                        .HasColumnType("int");

                    b.Property<int>("bola9")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LotoFacilDelay", (string)null);
                });

            modelBuilder.Entity("LottoLab.Models.LotoFacilRNA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concurso")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("Data")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("bola1")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola10")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola11")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola12")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola13")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola14")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola15")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola16")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola17")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola18")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola19")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola2")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola20")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola21")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola22")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola23")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola24")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola25")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola3")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola4")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola5")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola6")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola7")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola8")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("bola9")
                        .IsRequired()
                        .HasColumnType("char");

                    b.HasKey("Id");

                    b.ToTable("LotoFacilRNA", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
